/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_v1_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/triage-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Run */
        post: operations["create_run_api_v1_triage_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/triage-runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_triage_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/triage-runs/{run_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide Run */
        post: operations["decide_run_api_v1_triage_runs__run_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/triage-runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Events */
        get: operations["stream_events_api_v1_triage_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApproveDecision */
        ApproveDecision: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "approve";
        };
        /** AwaitingReviewRun */
        AwaitingReviewRun: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            draft: components["schemas"]["ResolutionBrief"];
            /** Evidence */
            evidence: components["schemas"]["EvidenceItem"][];
            prediction: components["schemas"]["PredictionBundle"];
            /** Review Reasons */
            review_reasons: string[];
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "awaiting_review";
            submission: components["schemas"]["IssueSubmission"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CompletedEventPayload */
        CompletedEventPayload: {
            snapshot: components["schemas"]["CompletedRun"];
        };
        /** CompletedRun */
        CompletedRun: {
            brief: components["schemas"]["ResolutionBrief"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Evidence */
            evidence: components["schemas"]["EvidenceItem"][];
            prediction: components["schemas"]["PredictionBundle"];
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "completed";
            submission: components["schemas"]["IssueSubmission"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DecisionAccepted */
        DecisionAccepted: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Status */
            status: string;
        };
        /** EditDecision */
        EditDecision: {
            brief: components["schemas"]["ResolutionBrief"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "edit";
        };
        /** EvidenceItem */
        EvidenceItem: {
            /** Excerpt */
            excerpt: string;
            /** Issue Number */
            issue_number?: number | null;
            /** Path */
            path?: string | null;
            /** Repository Sha */
            repository_sha: string;
            /** Score */
            score: number;
            /** Source Id */
            source_id: string;
            source_kind: components["schemas"]["SourceKind"];
            /**
             * Url
             * Format: uri
             */
            url: string;
        };
        /** FailedEventPayload */
        FailedEventPayload: {
            snapshot: components["schemas"]["FailedRun"];
        };
        /** FailedRun */
        FailedRun: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Code */
            error_code: string;
            /** Retryable */
            retryable: boolean;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "failed";
            submission: components["schemas"]["IssueSubmission"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** InvestigationStep */
        InvestigationStep: {
            /** Action */
            action: string;
            /** Citation Ids */
            citation_ids: string[];
            /** Rank */
            rank: number;
            /** Rationale */
            rationale: string;
        };
        /** IssueSubmission */
        IssueSubmission: {
            /** Body */
            body: string;
            /** Client Request Id */
            client_request_id: string;
            /** Title */
            title: string;
        };
        /**
         * IssueType
         * @enum {string}
         */
        IssueType: "bug" | "documentation" | "feature" | "question";
        /** PhaseEventPayload */
        PhaseEventPayload: {
            phase: components["schemas"]["RunningPhase"];
            snapshot: components["schemas"]["RunningRun"];
        };
        /** PredictionBundle */
        PredictionBundle: {
            /** Calibrated Confidence */
            calibrated_confidence: number;
            /** Classifier Version */
            classifier_version: string;
            issue_type: components["schemas"]["IssueType"];
            /** Predicted Close Days */
            predicted_close_days: number;
            /** Regressor Version */
            regressor_version: string;
        };
        /** QueuedEventPayload */
        QueuedEventPayload: {
            /**
             * Status
             * @default queued
             * @constant
             */
            status: "queued";
        };
        /** QueuedRun */
        QueuedRun: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "queued";
            submission: components["schemas"]["IssueSubmission"];
        };
        /** ReadyResponse */
        ReadyResponse: {
            /** Checks */
            checks: {
                [key: string]: boolean;
            };
            /** Mode */
            mode: string;
            /** Status */
            status: string;
        };
        /** RejectDecision */
        RejectDecision: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "reject";
            /** Reason */
            reason: string;
        };
        /** RejectedEventPayload */
        RejectedEventPayload: {
            snapshot: components["schemas"]["RejectedRun"];
        };
        /** RejectedRun */
        RejectedRun: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Reason */
            reason: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "rejected";
            submission: components["schemas"]["IssueSubmission"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ResolutionBrief */
        ResolutionBrief: {
            /** Citation Ids */
            citation_ids: string[];
            /** Investigation Steps */
            investigation_steps: components["schemas"]["InvestigationStep"][];
            /** Missing Information */
            missing_information: string[];
            /** Summary */
            summary: string;
        };
        /** ReviewEventPayload */
        ReviewEventPayload: {
            snapshot: components["schemas"]["AwaitingReviewRun"];
        };
        /** ReviewRequiredEvent */
        ReviewRequiredEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "review.required";
            payload: components["schemas"]["ReviewEventPayload"];
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Sequence */
            sequence: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** RunAccepted */
        RunAccepted: {
            /**
             * Events Url
             * Format: uri
             */
            events_url: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Snapshot Url
             * Format: uri
             */
            snapshot_url: string;
        };
        /** RunCompletedEvent */
        RunCompletedEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "run.completed";
            payload: components["schemas"]["CompletedEventPayload"];
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Sequence */
            sequence: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** RunFailedEvent */
        RunFailedEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "run.failed";
            payload: components["schemas"]["FailedEventPayload"];
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Sequence */
            sequence: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** RunPhaseEvent */
        RunPhaseEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "run.phase";
            payload: components["schemas"]["PhaseEventPayload"];
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Sequence */
            sequence: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** RunQueuedEvent */
        RunQueuedEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "run.queued";
            payload: components["schemas"]["QueuedEventPayload"];
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Sequence */
            sequence: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** RunRejectedEvent */
        RunRejectedEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "run.rejected";
            payload: components["schemas"]["RejectedEventPayload"];
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Sequence */
            sequence: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /**
         * RunningPhase
         * @enum {string}
         */
        RunningPhase: "predicting" | "retrieving" | "investigating" | "drafting" | "reviewing";
        /** RunningRun */
        RunningRun: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            phase: components["schemas"]["RunningPhase"];
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "running";
            submission: components["schemas"]["IssueSubmission"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * SourceKind
         * @enum {string}
         */
        SourceKind: "documentation" | "code" | "resolved_issue";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_api_v1_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
        };
    };
    create_run_api_v1_triage_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueSubmission"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_triage_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueuedRun"] | components["schemas"]["RunningRun"] | components["schemas"]["AwaitingReviewRun"] | components["schemas"]["CompletedRun"] | components["schemas"]["RejectedRun"] | components["schemas"]["FailedRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_run_api_v1_triage_runs__run_id__decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveDecision"] | components["schemas"]["EditDecision"] | components["schemas"]["RejectDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_api_v1_triage_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-sent RunEvent frames with ordered replay IDs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunQueuedEvent"] | components["schemas"]["RunPhaseEvent"] | components["schemas"]["ReviewRequiredEvent"] | components["schemas"]["RunCompletedEvent"] | components["schemas"]["RunRejectedEvent"] | components["schemas"]["RunFailedEvent"];
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
